'use client';

import Link from 'next/link';

import { MarketingFooter, MarketingHeader, useMarketingLocale } from '../../components/marketing/marketing-shell';
import { useI18n } from '../../lib/i18n/index';

export default function TermsPage() {
  const [locale, setLocale] = useMarketingLocale();
  const { t } = useI18n(locale);

  return (
    <div className="marketing-page">
      <MarketingHeader locale={locale} onLocaleChange={setLocale} />
      <main className="marketing-container py-16 max-w-3xl">
        <h1 className="text-3xl font-semibold text-ink mb-2">{t('legal.termsTitle')}</h1>
        <p className="text-sm text-ink-3 mb-8">{t('legal.lastUpdated')}</p>

        <section className="prose-section space-y-6 text-ink-2 text-sm leading-relaxed">
          <div>
            <h2 className="text-lg font-semibold text-ink mb-2">1. Service</h2>
            <p>
              Montenegrina provides voice and chat AI agents with knowledge retrieval for organizations. By creating
              an account you agree to use the service in compliance with applicable law.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-ink mb-2">2. Accounts</h2>
            <p>
              You are responsible for safeguarding your credentials and for activity under your workspace. You must
              provide accurate registration information.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-ink mb-2">3. Acceptable use</h2>
            <p>
              You may not use Montenegrina to distribute malware, harass users, violate privacy, or process data you
              are not authorized to handle. We may suspend accounts that abuse quotas or threaten platform stability.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-ink mb-2">4. AI outputs</h2>
            <p>
              Agent responses are generated by third-party AI providers. You are responsible for reviewing outputs before
              relying on them in regulated or high-risk contexts.
            </p>
          </div>
          <div>
            <h2 className="text-lg font-semibold text-ink mb-2">5. Contact</h2>
            <p>
              Questions about these terms:{' '}
              <a href={`mailto:${t('legal.contactEmail')}`} className="text-accent">
                {t('legal.contactEmail')}
              </a>
            </p>
          </div>
        </section>

        <p className="mt-10 text-sm">
          <Link href="/privacy" className="text-accent hover:underline">
            {t('legal.privacyTitle')}
          </Link>
        </p>
      </main>
      <MarketingFooter locale={locale} />
    </div>
  );
}
