/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getLiveness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/ready": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listOrganizations"];
        put?: never;
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteOrganization"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/organizations/{organizationId}/memberships": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listMemberships"];
        put?: never;
        post: operations["createMembership"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listAgents"];
        put?: never;
        post: operations["createAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getAgent"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateAgent"];
        trace?: never;
    };
    "/v1/agents/{agentId}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createAgentVersion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agentId}/publish": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["publishAgent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transcriptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createTranscription"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/responses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createResponse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/speech": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createSpeech"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createConversation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getConversation"];
        put?: never;
        post?: never;
        delete: operations["deleteConversation"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversationId}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getTranscript"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversationId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["streamConversationEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversationId}/handoff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["requestHandoff"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/conversations/{conversationId}/tool-invocations/{invocationId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["confirmToolInvocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agentId}/realtime-sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createRealtimeSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/agents/{agentId}/calls": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createCall"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/bases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKnowledgeBases"];
        put?: never;
        post: operations["createKnowledgeBase"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/bases/{knowledgeBaseId}/assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKnowledgeBaseAssignments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/retrieve/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["testKnowledgeRetrieval"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/ingestion-jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getIngestionJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/documents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listKnowledgeDocuments"];
        put?: never;
        post: operations["createKnowledgeDocument"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/knowledge/documents/{documentId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteKnowledgeDocument"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listTools"];
        put?: never;
        post: operations["createTool"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tools/{toolId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateTool"];
        trace?: never;
    };
    "/v1/evaluations/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createEvaluationRun"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evaluations/runs/{runId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getEvaluationRun"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/usage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getUsage"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ErrorEnvelope: {
            error: {
                code: string;
                message: string;
                requestId: string;
                retryable: boolean;
                details?: {
                    [key: string]: unknown;
                };
            };
        };
        /** @constant */
        Language: "cnr";
        /** @enum {string} */
        MembershipRole: "OWNER" | "ADMIN" | "DEVELOPER" | "VIEWER";
        /** @enum {string} */
        SttLanguage: "sr" | "hr" | "bs" | "multi";
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        Session: {
            user: components["schemas"]["User"];
            csrfToken: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName?: string;
            /** Format: date-time */
            createdAt: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            name: string;
            slug: string;
            /** Format: date-time */
            createdAt: string;
        };
        CreateOrganizationRequest: {
            name: string;
            slug: string;
        };
        Membership: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            userId: string;
            role: components["schemas"]["MembershipRole"];
        };
        CreateApiKeyRequest: {
            name: string;
            /** @enum {string} */
            environment: "development" | "staging" | "production";
            permissions: string[];
        };
        ApiKeyCreated: {
            /** Format: uuid */
            id: string;
            prefix: string;
            /** @description Returned once and never stored verbatim. */
            key: string;
        };
        Agent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            name: string;
            slug: string;
            description?: string;
            language: components["schemas"]["Language"];
            /** Format: uuid */
            publishedVersionId?: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateAgentRequest: {
            name: string;
            slug: string;
            description?: string;
        };
        UpdateAgentRequest: {
            name?: string;
            description?: string;
        };
        AgentVersion: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            agentId: string;
            version: number;
            /** @enum {string} */
            status: "DRAFT" | "PUBLISHED" | "RETIRED";
            config: components["schemas"]["AgentConfiguration"];
            /** Format: date-time */
            createdAt: string;
        };
        CreateAgentVersionRequest: {
            config: components["schemas"]["AgentConfiguration"];
        };
        AgentConfiguration: {
            systemPrompt: string;
            languageProfile: {
                /** @enum {string} */
                script: "LATIN" | "CYRILLIC";
                ijekavian: boolean;
                glossaryIds?: string[];
                pronunciationIds?: string[];
            };
            routingPolicy: {
                /** @enum {string} */
                mode: "real";
                /** @enum {string} */
                pipelineMode: "controlled" | "direct_realtime";
                sttLanguage?: components["schemas"]["SttLanguage"];
                llmModel?: string;
                ttsModel?: string;
                realtimeModel?: string;
                /** @default true */
                fallbackAllowed: boolean;
                allowedProviders?: string[];
                allowedRegions?: string[];
            };
            retention: {
                transcriptDays: number;
                recordAudio: boolean;
                audioDays?: number;
            };
            toolIds?: string[];
            knowledgeSourceIds?: string[];
            knowledgeBaseIds?: string[];
            /** @default false */
            sensitiveWritesEnabled: boolean;
        };
        Transcription: {
            language: components["schemas"]["Language"];
            originalText: string;
            normalizedText: string;
            warnings: string[];
            provider: components["schemas"]["ProviderSummary"];
        };
        CreateResponseRequest: {
            /** Format: uuid */
            agentId: string;
            /** Format: uuid */
            conversationId?: string;
            input: string;
            /** @default false */
            stream: boolean;
        };
        GeneratedResponse: {
            language: components["schemas"]["Language"];
            text: string;
            originalText: string;
            warnings: string[];
            citations: components["schemas"]["Citation"][];
            provider: components["schemas"]["ProviderSummary"];
        };
        CreateSpeechRequest: {
            /** Format: uuid */
            agentId: string;
            text: string;
            /**
             * @default wav
             * @enum {string}
             */
            format: "wav" | "pcm";
        };
        ProviderSummary: {
            provider: string;
            model: string;
            latencyMs: number;
            usage: components["schemas"]["Usage"];
            fallbackHistory?: {
                provider: string;
                code: string;
                retryable?: boolean;
            }[];
        };
        Usage: {
            provider?: string;
            operation?: string;
            inputTokens?: number;
            outputTokens?: number;
            audioInputSeconds?: number;
            audioOutputSeconds?: number;
            characters?: number;
            estimatedCostUsd?: number;
        };
        Conversation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
            /** Format: uuid */
            agentId: string;
            /** @enum {string} */
            channel: "TEXT" | "BROWSER" | "SIP" | "BATCH";
            state: components["schemas"]["ConversationState"];
            language: components["schemas"]["Language"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        /** @enum {string} */
        ConversationState: "INITIALIZING" | "LISTENING" | "TRANSCRIBING" | "THINKING" | "TOOL_PENDING" | "SPEAKING" | "INTERRUPTED" | "HANDOFF_PENDING" | "HANDED_OFF" | "COMPLETED" | "FAILED";
        TranscriptSegment: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            speaker: "USER" | "ASSISTANT" | "HUMAN";
            originalText: string;
            normalizedText: string;
            startedAtMs: number;
            endedAtMs?: number;
            final: boolean;
        };
        RealtimeSession: {
            /** Format: uuid */
            conversationId: string;
            roomName: string;
            participantToken: string;
            livekitUrl: string;
            /** Format: date-time */
            expiresAt: string;
            language: components["schemas"]["Language"];
        };
        Citation: {
            /** Format: uuid */
            documentId: string;
            /** Format: uuid */
            documentVersionId: string;
            /** Format: uuid */
            chunkId: string;
            title: string;
            page?: number;
            section?: string;
            score?: number;
        };
        Document: {
            /** Format: uuid */
            id: string;
            title: string;
            /** @enum {string} */
            status: "UPLOADED" | "SCANNING" | "PROCESSING" | "READY" | "FAILED" | "QUARANTINED" | "DELETING";
            version: number;
            errorCode?: string;
            /** Format: date-time */
            createdAt: string;
        };
        ToolDefinition: {
            name: string;
            version: number;
            description: string;
            /** @enum {string} */
            riskClass: "READ_PUBLIC" | "READ_CUSTOMER" | "WRITE_REVERSIBLE" | "WRITE_SENSITIVE";
            /** @enum {string} */
            handler: "sandbox.product_lookup" | "sandbox.appointment_availability" | "sandbox.appointment_create" | "sandbox.request_status" | "sandbox.handoff" | "fixed_https";
            inputSchema: {
                [key: string]: unknown;
            };
            outputSchema?: {
                [key: string]: unknown;
            };
            connectorConfig?: {
                [key: string]: unknown;
            };
            /** @default true */
            enabled: boolean;
        };
        Tool: components["schemas"]["ToolDefinition"] & {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            organizationId: string;
        };
        ToolInvocation: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** Format: uuid */
            toolId: string;
            /** @enum {string} */
            status: "PROPOSED" | "AWAITING_CONFIRMATION" | "RUNNING" | "COMPLETED" | "REJECTED" | "FAILED";
            input: {
                [key: string]: unknown;
            };
            result?: {
                [key: string]: unknown;
            };
            errorCode?: string;
        };
        Handoff: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            conversationId: string;
            /** @enum {string} */
            status: "REQUESTED" | "ACCEPTED" | "COMPLETED" | "FAILED";
            /** Format: date-time */
            requestedAt: string;
        };
        Deletion: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
        };
        CreateEvaluationRunRequest: {
            /** Format: uuid */
            datasetId: string;
            variants: {
                name: string;
                /** @enum {string} */
                pipeline: "text" | "realtime";
                sttLanguage?: components["schemas"]["SttLanguage"];
                /** Format: uuid */
                promptVersionId?: string;
                voiceId?: string;
                endpointing?: {
                    [key: string]: unknown;
                };
            }[];
        };
        EvaluationRun: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "QUEUED" | "RUNNING" | "COMPLETED" | "FAILED";
            /** Format: uri */
            reportUrl?: string;
            metrics?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
    };
    responses: {
        /** @description Typed error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorEnvelope"];
            };
        };
        /** @description Health status */
        Health: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "ok" | "degraded";
                    /** Format: date-time */
                    timestamp: string;
                    checks?: {
                        [key: string]: string;
                    };
                };
            };
        };
        /** @description Browser session */
        Session: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Session"];
            };
        };
        /** @description Organization */
        Organization: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Organization"];
            };
        };
        /** @description Organizations */
        OrganizationList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Organization"][];
                };
            };
        };
        /** @description Agent */
        Agent: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Agent"];
            };
        };
        /** @description Agents */
        AgentList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Agent"][];
                    nextCursor?: string;
                };
            };
        };
        /** @description Immutable agent version */
        AgentVersion: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AgentVersion"];
            };
        };
        /** @description Normalized transcription */
        Transcription: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Transcription"];
            };
        };
        /** @description Montenegrin response */
        GeneratedResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["GeneratedResponse"];
            };
        };
        /** @description Conversation */
        Conversation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Conversation"];
            };
        };
        /** @description Knowledge document */
        Document: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Document"];
            };
        };
        /** @description Knowledge documents */
        DocumentList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Document"][];
                };
            };
        };
        /** @description Tool definition */
        Tool: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Tool"];
            };
        };
        /** @description Tool definitions */
        ToolList: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    items: components["schemas"]["Tool"][];
                };
            };
        };
        /** @description Tool invocation */
        ToolInvocation: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ToolInvocation"];
            };
        };
        /** @description Handoff */
        Handoff: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Handoff"];
            };
        };
        /** @description Asynchronous deletion */
        Deletion: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Deletion"];
            };
        };
        /** @description Evaluation run */
        EvaluationRun: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["EvaluationRun"];
            };
        };
    };
    parameters: {
        AgentId: string;
        ConversationId: string;
        OrganizationId: string;
        IdempotencyKey: string;
        Cursor: string;
        Limit: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getLiveness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Health"];
            503: components["responses"]["Error"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Session"];
            401: components["responses"]["Error"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["OrganizationList"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrganizationRequest"];
            };
        };
        responses: {
            201: components["responses"]["Organization"];
            409: components["responses"]["Error"];
        };
    };
    deleteOrganization: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Deletion"];
            403: components["responses"]["Error"];
        };
    };
    listMemberships: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Memberships */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Membership"][];
                    };
                };
            };
        };
    };
    createMembership: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                organizationId: components["parameters"]["OrganizationId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: email */
                    email: string;
                    role: components["schemas"]["MembershipRole"];
                };
            };
        };
        responses: {
            /** @description Membership created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Membership"];
                };
            };
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateApiKeyRequest"];
            };
        };
        responses: {
            /** @description API key shown once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiKeyCreated"];
                };
            };
        };
    };
    listAgents: {
        parameters: {
            query?: {
                cursor?: components["parameters"]["Cursor"];
                limit?: components["parameters"]["Limit"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["AgentList"];
        };
    };
    createAgent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentRequest"];
            };
        };
        responses: {
            201: components["responses"]["Agent"];
            400: components["responses"]["Error"];
        };
    };
    getAgent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agentId: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Agent"];
            404: components["responses"]["Error"];
        };
    };
    updateAgent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                agentId: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAgentRequest"];
            };
        };
        responses: {
            200: components["responses"]["Agent"];
        };
    };
    createAgentVersion: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                agentId: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAgentVersionRequest"];
            };
        };
        responses: {
            201: components["responses"]["AgentVersion"];
        };
    };
    publishAgent: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                agentId: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    versionId: string;
                };
            };
        };
        responses: {
            200: components["responses"]["Agent"];
            422: components["responses"]["Error"];
        };
    };
    createTranscription: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    audio: string;
                    /** Format: uuid */
                    agentId?: string;
                    sttLanguage?: components["schemas"]["SttLanguage"];
                };
            };
        };
        responses: {
            200: components["responses"]["Transcription"];
        };
    };
    createResponse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateResponseRequest"];
            };
        };
        responses: {
            200: components["responses"]["GeneratedResponse"];
            400: components["responses"]["Error"];
        };
    };
    createSpeech: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSpeechRequest"];
            };
        };
        responses: {
            /** @description Streamed audio */
            200: {
                headers: {
                    "X-Request-Id"?: string;
                    "X-Provider"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "audio/wav": string;
                    "audio/pcm": string;
                };
            };
        };
    };
    createConversation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    agentId: string;
                    /** @enum {string} */
                    channel: "TEXT" | "BROWSER" | "SIP" | "BATCH";
                };
            };
        };
        responses: {
            201: components["responses"]["Conversation"];
        };
    };
    getConversation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["Conversation"];
            404: components["responses"]["Error"];
        };
    };
    deleteConversation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Deletion"];
        };
    };
    getTranscript: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered transcript */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @constant */
                        language: "cnr";
                        segments: components["schemas"]["TranscriptSegment"][];
                    };
                };
            };
        };
    };
    streamConversationEvents: {
        parameters: {
            query?: never;
            header?: {
                "Last-Event-ID"?: string;
            };
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resumable normalized event stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
    requestHandoff: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversationId: components["parameters"]["ConversationId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    reason?: string;
                };
            };
        };
        responses: {
            202: components["responses"]["Handoff"];
        };
    };
    confirmToolInvocation: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                conversationId: components["parameters"]["ConversationId"];
                invocationId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    confirmed: boolean;
                    confirmationText: string;
                };
            };
        };
        responses: {
            200: components["responses"]["ToolInvocation"];
        };
    };
    createRealtimeSession: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                agentId: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    participantName?: string;
                };
            };
        };
        responses: {
            /** @description LiveKit session credentials */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RealtimeSession"];
                };
            };
        };
    };
    createCall: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                agentId: components["parameters"]["AgentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    to: string;
                };
            };
        };
        responses: {
            202: components["responses"]["Conversation"];
        };
    };
    listKnowledgeBases: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Knowledge bases */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createKnowledgeBase: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created knowledge base */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listKnowledgeBaseAssignments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                knowledgeBaseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Agent assignments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    testKnowledgeRetrieval: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Retrieval test results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getIngestionJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ingestion job status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listKnowledgeDocuments: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["DocumentList"];
        };
    };
    createKnowledgeDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: uuid */
                    knowledgeBaseId: string;
                    /** Format: uuid */
                    agentId?: string;
                    title: string;
                    /** Format: binary */
                    file: string;
                };
                "application/json": {
                    /** Format: uuid */
                    agentId: string;
                    title: string;
                    text: string;
                    /** Format: uri */
                    sourceUrl?: string;
                };
            };
        };
        responses: {
            202: components["responses"]["Document"];
        };
    };
    deleteKnowledgeDocument: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            202: components["responses"]["Deletion"];
        };
    };
    listTools: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ToolList"];
        };
    };
    createTool: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolDefinition"];
            };
        };
        responses: {
            201: components["responses"]["Tool"];
        };
    };
    updateTool: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                toolId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolDefinition"];
            };
        };
        responses: {
            200: components["responses"]["Tool"];
        };
    };
    createEvaluationRun: {
        parameters: {
            query?: never;
            header: {
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEvaluationRunRequest"];
            };
        };
        responses: {
            202: components["responses"]["EvaluationRun"];
        };
    };
    getEvaluationRun: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                runId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["EvaluationRun"];
        };
    };
    getUsage: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Usage grouped by provider and operation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        items: components["schemas"]["Usage"][];
                    };
                };
            };
        };
    };
}
